version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: feerosh_postgres
    restart: always
    environment:
      POSTGRES_USER: feerosh_user
      POSTGRES_PASSWORD: feerosh_password
      POSTGRES_DB: feerosh_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: feerosh_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@feerosh.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
